---
rawGenesisConfig:
  blockchain:
    nodes:
      generate: true
      count: 4

azure:
  # the script/bootstrap.sh uses the name 'default-pod-identity' so only change this if you altered the name
  identityName: default-pod-identity
  keyvaultName: azure-keyvault
